// <auto-generated />
using LibraryUI.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryUI.Migrations
{
    [DbContext(typeof(BooksContext))]
    [Migration("20230606102302_initial-migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryUI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Толстой",
                            ISBN = "123456789",
                            Title = "Война и Мир"
                        },
                        new
                        {
                            Id = 2,
                            Author = "J. K. Rowling",
                            ISBN = "12345678910",
                            Title = "Harry Potter Philosopher's Stone"
                        },
                        new
                        {
                            Id = 3,
                            Author = "J. K. Rowling",
                            ISBN = "123456789a",
                            Title = "Harry Potter Chamber of Secrets"
                        },
                        new
                        {
                            Id = 4,
                            Author = "J. K. Rowling",
                            ISBN = "123456789b",
                            Title = "Harry Potter CPrisoner of Azkaban"
                        },
                        new
                        {
                            Id = 5,
                            Author = "J. K. Rowling",
                            ISBN = "123456789c",
                            Title = "Harry Potter Goblet of Fire"
                        },
                        new
                        {
                            Id = 6,
                            Author = "J. K. Rowling",
                            ISBN = "123456789d",
                            Title = "Harry Potter Order of the Phoenix"
                        },
                        new
                        {
                            Id = 7,
                            Author = "J. K. Rowling",
                            ISBN = "123456789e",
                            Title = "Harry Potter Half-Blood Prince"
                        },
                        new
                        {
                            Id = 8,
                            Author = "J. K. Rowling",
                            ISBN = "123456789f",
                            Title = "Harry Potter Deathly Hallows"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
